config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  #get 'welcome/index'

  #poner rutas especiales
  #get 'especial', to: 'welcome#index'

  resources :articles #controlador RESTFUL (rutas y acciones definidiadas)
  #except: [:delete]
  #only: [:delete]

  #es lo mismo qué
  	# get "/articles" 			index
  	# post "/articles" 			create
  	# delete "/articles:id"  destroy
  	# get "articles/:id" 		show
  	# get "/articles/new" 		new
  	# get "/articles/:id/edit" 	edit
  	# patch "/articles/:id" 	update
  	# put "/articles/:id"  		update
  

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	#campos
		#id
		#title
		#body
		#visits_count

	#validaciones
	# uniqueness: true valida que esa propiedad no se repita
	# format: {with: /expresion_regular/}
	validates :title, presence: true
	validates :body, presence:true, length: { minimum: 20}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	#ejemplos métodos active records básico
	# all = obtiene todos los registros
	# find = encuentra registro por su id
	# all.count = el número de registros
	# find_by (atributo: "dato") = el regsitro que coincidan con la busqueda, siempre retorna uno
	# where ("title LIKE ?", "%lo_que_quieres_que_coincida%") = reemplazar variables por signo de interrgación, después de la coma, devuelve más de uno
	# where ("id = ? OR title = ?", params[:id], params[:titile])
	# where.not ("title LIKE ?", "%lo_que_quieres_que_coincida%") = trae los que no coinciden con lo que estás buscando
	# destroy = elimna el objeto de la base de datos
	# @article.update_attibutes({titile: 'Nuevo título'})


	# GET /articles
	def index
		#trae todos los registros de la base de datos
		# de la tabla article
		@articles = Article.all
	end

	# GET /articles/:id
	def show
		#params es un hash con todo los parametros que se mandaron al servidor web
		@article = Article.find(params[:id])
	end

	#Get /articles/new
	def new
		@article = Article.new
	end

	#POST /articles
	def create
		@article = Article.new(article_params)

		# esto funciona pero pudiera llegar a ser inseguro (inyección de código), por lo que se usará strong params
		# @article = Article.new(title: params[:article][:title], 
		# 						body: params[:article][:body])

		# para validarque se cumplieron las condiciones del modelo
		# @article.valid?
		# @article.invalid?
		if @article.save
			redirect_to @article
		else
			render :new
		end
	end

	# get "/articles/:id/edit"
	def edit
		@article = Article.find(params[:id])
	end

	# put "/articles/:id"
	def update
		@article = Article.find(params[:id])

		if @article.update(article_params)
			redirect_to @article
		else
			render :edit
		end
	end

	#DELETE /articles:id
	def destroy
		@article = Article.find(params[:id])
		@article.destroy # elimina el objeto de la base de datos
		redirect_to articles_path
	end

	private
	#strong params
	def article_params
		params.require(:article).permit(:title,:body)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  #para hacer que todas las acciones del controller usen el mismo layout
  #render layout: 'otherLayout'

  def index
  end

  # para hacer que una acción especifica use otro layout
  # def otherAction
  # 	render layout: 'otherLayout'
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%# si la variable no la están mandando, creala con este valor%>
<% name_page ||= "Crear" %>
<h1><%= name_page %> artículo</h1>
<%# cuando form_for recibe un objeto que no está guardado en la base de datos, el post lo manda a create. SI ya existe lo manda update %>
<%= form_for(@article) do |f| %>
	<%# muestra las validaciones que no se pasaron
		se puede acceder a ella, por que en el create/update se dice que se renderice la vista "new"
	%>
	<% @article.errors.full_messages.each do |message| %>
		<div class="be-blue white field">
			* <%= message %>
		</div>
	<%end%>
	<div class="field">
		<%= f.text_field :title, placeholder: "Título", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.text_area :body, placeholder: "Escríbe tu artículo aquí", style: "height:250px;", class:"form-control" %>
	</div>
	<div class="field">
		<%= f.submit "Guardar", class: "btn be-blue white" %>
	</div>
<% end %>

app/views/articles/edit.html.erb
<div style="width: 80%; margin:0 auto;">
	<%= render "form", name_page: "Editar" %>
</div>

app/views/articles/index.html.erb
<%# @articles.inspect %>

<% @articles.each do | article | %>

<h1>Título: <%= link_to article.title, article %></h1>
<p>Cuerpo: <%= article.body %></p>
<p>Visitas: <%= article.visits_count %></p>
	<%= link_to "Eliminar", article, method: :delete, class: "btn be-blue white" %>
</br>
</br>
<% end %>

app/views/articles/new.html.erb
<div style="width: 80%; margin:0 auto;">
	<%= render "form", name_page: "Crear" %>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p> <%= @article.body %> </p>
</br>
<%= link_to "Editar", edit_article_path(@article), class: "btn be-blue white" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Blog</title>
		<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Open+Sans" rel="stylesheet">

		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= csrf_meta_tags %>

	</head>
	<body>
		<%= render "partials/navigation" %>
		
		<p class="notice"><%= notice %></p>
		<p class="alert"><%= alert %></p>

		<%= yield %>
	</body>
</html>

app/views/partials/_navigation.html.erb
<header>
	<nav class="be-blue white large-padding">
		<ul class="no-list row center-xs middle-xs">
			<li class="col-md">
				<h1 class="no-margin" id="logo">Blog del Tole</h1>
			</li>
			<li class="col-md">
				<%= link_to "Inicio", root_path %>
			</li>
			<li class="col-md">
				Diseño
			</li>
			<li class="col-md">
				Programación
			</li>
			<li class="col-md">
				Tecnología
			</li>
			<% if user_signed_in? %>
				<li class="col-md">
					<%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete %>
				</li>
			<% else %>
				<li class="col-md">
					<%= link_to "Iniciar sesión", new_user_session_path %>
				</li>
				<li class="col-md">
					<%= link_to "Crear cuenta", new_user_registration_path %>
				</li>
			<% end %>
		</ul>
	</nav>
</header>

app/views/welcome/index.html.erb
<% if user_signed_in? %>
	<h1>¡Bienvenido <%= current_user.email%> !</h1>
<% end %>